name: GitHub Vault Secret Management

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conditional-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Install pytest
        run: pip install pytest
        
      - name: Run integration tests
        run: python -m pytest tests/
        env:
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
